/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_usbregistration_app_usbnative_NativeUsb */

#ifndef _Included_com_usbregistration_app_usbnative_NativeUsb
#define _Included_com_usbregistration_app_usbnative_NativeUsb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_usbregistration_app_usbnative_NativeUsb
 * Method:    enumerateUsbDevices
 * Signature: ()[Lcom/usbregistration/app/usbnative/USBItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_usbregistration_app_usbnative_NativeUsb_enumerateUsbDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
